### ISSUE TITLE
ReferenceError: emit is not defined

### ISSUE THREAD

**Issue by jedi4ever** [mcollina/docker-allcontainers#1]
I'm using this lib through docker/logentries
https://github.com/nearform/docker-logentries/blob/master/index.js

I receive an error after some time: `ReferenceError: emit is not defined`

```
logentries_1 |
logentries_1 | /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:47
logentries_1 |           return setTimeout(emit, 20)
logentries_1 |                             ^
logentries_1 | ReferenceError: emit is not defined
logentries_1 |     at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:47:29
logentries_1 |     at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:201:5
logentries_1 |     at Modem.buildPayload (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:222:7)
logentries_1 |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:183:14)
logentries_1 |     at IncomingMessage.emit (events.js:117:20)
logentries_1 |     at _stream_readable.js:944:16
logentries_1 |     at process._tickCallback (node.js:448:13)
ops_logentries_1 exited with code 8
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by mcollina** [comment]
Fixed and released here, it will be in the new release of docker-logentries https://github.com/nearform/docker-logentries/pull/16.

**Comment by jedi4ever** [comment]
thx @mcollina
