### ISSUE TITLE
Error in JSON parse

### ISSUE THREAD

**Issue by megastef** [mcollina/docker-allcontainers#9]
Hi, 

I've got an error in line https://github.com/mcollina/docker-allcontainers/blob/master/allcontainers.js#L27 in version 0.4.0. I think JSON.parse() needs a try/catch.

The error remained until Docker daemon got restarted - then it was fine again. Too bad, that I could not catch the output from dockerd.  

```
2016-06-13T17:01:11.769Z - ERROR - UncaughtException:SyntaxError: Unexpected token { in JSON at position 346
  SyntaxError: Unexpected token { in JSON at position 346
    at Object.parse (native)
    at DestroyableTransform._transform (/Users/stefan/sematext/sematext-agent-docker/node_modules/docker-allcontainers/allcontainers.js:27:21)
    at DestroyableTransform.Transform._read (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/stefan/sematext/sematext-agent-docker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

**Comment by megastef** [comment]
Solved in PR https://github.com/mcollina/docker-allcontainers/pull/10
